### ISSUE TITLE
Advanced stats (the weekly version) returns incomplete data

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/pfr_scrapR#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

-

### Describe the bug

nflreadr::load_pfr_advstats(2022) returns data of Super Bowl only

### Reprex

```r
r
pfr <- nflreadr::load_pfr_advstats(2022)
dplyr::glimpse(pfr)
#> Rows: 2
#> Columns: 24
#> $ game_id               <chr> "2022_22_KC_PHI", "2022_22_KC_PHI"
#> $ pfr_game_id           <chr> "202302120phi", "202302120phi"
#> $ season                <int> 2022, 2022
#> $ week                  <int> 22, 22
#> $ game_type             <chr> "SB", "SB"
#> $ team                  <chr> "PHI", "KC"
#> $ opponent              <chr> "KC", "PHI"
#> $ pfr_player_name       <chr> "Jalen Hurts", "Patrick Mahomes"
#> $ pfr_player_id         <chr> "HurtJa00", "MahoPa00"
#> $ passing_drops         <dbl> 1, 0
#> $ passing_drop_pct      <dbl> 0.029, 0.000
#> $ receiving_drop        <dbl> NA, NA
#> $ receiving_drop_pct    <dbl> NA, NA
#> $ passing_bad_throws    <dbl> 3, 3
#> $ passing_bad_throw_pct <dbl> 0.088, 0.120
#> $ times_sacked          <dbl> 2, 0
#> $ times_blitzed         <dbl> 15, 9
#> $ times_hurried         <dbl> 5, 2
#> $ times_hit             <dbl> 2, 5
#> $ times_pressured       <dbl> 9, 7
#> $ times_pressured_pct   <dbl> 0.214, 0.233
#> $ def_times_blitzed     <dbl> NA, NA
#> $ def_times_hurried     <dbl> NA, NA
#> $ def_times_hitqb       <dbl> NA, NA
```

<sup>Created on 2023-06-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
```


### Expected Behavior

all 2022 data 

### nflverse_sitrep

```r
── System Info ──────────────────────────────────────────────────────────────
• R version 4.3.1 (2023-06-16 ucrt)   • Running under: Windows 10 x64 (build 19045)
── nflverse Packages ────────────────────────────────────────────────────────
• nflreadr (1.3.2.03)    • nflseedR (1.2.0)         
• nflfastR (4.5.1.9001)  • nflplotR (1.1.0.9004)    
── nflverse Options ─────────────────────────────────────────────────────────
No options set for nflreadr, nflfastR, nflseedR, and nflplotR
── nflverse Dependencies ────────────────────────────────────────────────────
• cachem      (1.0.8)       • hms        (1.1.3)    • proto        (1.0.0)    
• cli         (3.6.1)       • isoband    (0.2.7)    • purrr        (1.0.1)    
• codetools   (0.2-19)      • janitor    (2.2.0)    • R6           (2.5.1)    
• colorspace  (2.1-0)       • jsonlite   (1.8.5)    • rappdirs     (0.3.3)    
• cpp11       (0.4.3)       • labeling   (0.4.2)    • RColorBrewer (1.1-3)    
• curl        (5.0.1)       • lattice    (0.21-8)   • Rcpp         (1.0.10)   
• data.table  (1.14.8)      • lifecycle  (1.0.3)    • rlang        (1.1.1)    
• digest      (0.6.31)      • listenv    (0.9.0)    • scales       (1.2.1)    
• dplyr       (1.1.2)       • lubridate  (1.9.2)    • snakecase    (0.11.0)   
• fansi       (1.0.4)       • magick     (2.7.4)    • stringi      (1.7.12)   
• farver      (2.1.1)       • magrittr   (2.0.3)    • stringr      (1.5.0)    
• fastmap     (1.1.1)       • MASS       (7.3-60)   • tibble       (3.2.1)    
• fastrmodels (1.0.2.9001)  • Matrix     (1.5-4.1)  • tidyr        (1.3.0)    
• furrr       (0.3.1)       • memoise    (2.0.1)    • tidyselect   (1.2.0)    
• future      (1.32.0)      • mgcv       (1.8-42)   • timechange   (0.2.0)    
• generics    (0.1.3)       • munsell    (0.5.0)    • utf8         (1.2.3)    
• ggplot2     (3.4.2)       • nlme       (3.1-162)  • vctrs        (0.6.3)    
• globals     (0.16.2)      • parallelly (1.36.0)   • viridisLite  (0.4.2)    
• glue        (1.6.2)       • pillar     (1.9.0)    • withr        (2.5.0)    
• gsubfn      (0.7)         • pkgconfig  (2.0.3)    • xgboost      (1.7.5.1)  
• gtable      (0.3.3)       • progressr  (0.13.0)     
─────────────────────────────────────────────────────────────────────────────
```
```


### Screenshots

_No response_

### Additional context

_No response_

**Comment by mrcaseb** [comment]
Maybe related to #23 I don't know

**Comment by mrcaseb** [comment]
Diving deeper, I think this line is the bad boy

https://github.com/nflverse/nflverse-pfr/blob/b9b75151d4e3577b46eff83edb5b7214cbbea2ea/auto/update_adv_stats.R#L65

I think this snippet was supposed to load all previously scraped games. The filter should exclude games that have been scraped in that run. However, it excludes all games in the `completed_games` dataframe which means we have removed all previously scraped games and save the most recent game only. LOL? So we have to reload all the games, being careful with PFR so that the runner is not banned. 
```r
archived_games <- piggyback::pb_download_url(
    file = "advstats_game.rds",
    repo = "nflverse/nflverse-pfr",
    tag = "advstats_raw") |>
    nflreadr::rds_from_url() |>
    dplyr::filter(!pfr_game_id %in% completed_games$pfr_game_id)
```
What the code actually should look like imo
```r
archived_games <- piggyback::pb_download_url(
    file = "advstats_game.rds",
    repo = "nflverse/nflverse-pfr",
    tag = "advstats_raw") |>
    nflreadr::rds_from_url() |>
    dplyr::filter(!pfr_game_id %in% scrape_games$pfr_game_id)
```

**Comment by vest-sports** [comment]
Any possibility this gets fixed by season start?  I'm just trying to see if I need to contingency plan a proxy for this dataset (pressures in particular).  Thanks!

**Comment by alecglen** [comment]
@mrcaseb Thanks for your work on this!

FYI I just viewed the updated release files, and they're in much better shape than before. However, there still appears to be some missing data in the first part of the season.
<img width="546" alt="image" src="https://github.com/nflverse/nflverse-pfr/assets/28493454/77a30715-7b80-4024-bdcf-318c45065bdb">

**Comment by mrcaseb** [comment]
> @mrcaseb Thanks for your work on this!
> 
> 
> 
> FYI I just viewed the updated release files, and they're in much better shape than before. However, there still appears to be some missing data in the first part of the season.
> 
> <img width="546" alt="image" src="https://github.com/nflverse/nflverse-pfr/assets/28493454/77a30715-7b80-4024-bdcf-318c45065bdb">
> 
> 
> 
> 

I know, games will be added slowly over the next couple days. We are trying to be polite to PFR.

**Comment by mrcaseb** [comment]
UPDATE: data should be complete now. All games of the 2018-2022 seasons

**Comment by alecglen** [comment]
Looks good! Thank you for your diligence sir 💯
